export const SET_TODOS = 'SET_TODOS';
export const CLEAR_TODOS_REQUESTED = 'CLEAR_TODOS_REQUESTED';
export const DELETE_TODO_REQUESTED = 'DELETE_TODO_REQUESTED';
export const UPDATE_TODO_REQUESTED = 'UPDATE_TODO_REQUESTED';
export const ADD_TODO_REQUESTED = 'ADD_TODO_REQUESTED';
export const GET_TODOS_REQUESTED = 'GET_TODOS_REQUESTED';
